name: Feature request
description: Suggest an idea for this project
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve
      description: What are you trying to do that tooned doesn't support today?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
    validations:
      required: false
